FROM ubuntu:24.04

ARG DNS=localhost
ARG HTTP_APP_PORT=8080

RUN apt-get update -y

####################################
## INSTALAMOS PAQUETES NECESARIOS
####################################
RUN apt-get install -y openjdk-11-jdk curl nodejs npm nginx

# Instalamos Angular CLI
RUN npm install -g @angular/cli@13

#################################
## CREAMOS DIRECTORIOS
#################################
RUN mkdir -p /srv/aplicaciones/backend

####################################
## COPIAMOS ENVIRONMENT y JARS
####################################
COPY environment/backend.env /srv/aplicaciones/backend/.env
COPY java/devsuTest* /srv/aplicaciones/backend/Backend.jar

##############################################
### INSTALAMOS ANGULAR
##############################################
COPY submodules/frontend/frontend /srv/aplicaciones/frontend
COPY environment/frontend.ts /srv/aplicaciones/frontend/src/environments/environment.prod.ts

WORKDIR /srv/aplicaciones/frontend
RUN npm install && ng build --configuration production

#################################
### CONFIGURAMOS NGINX
#################################
COPY nginx/* /etc/nginx/sites-available/
RUN ln -s /etc/nginx/sites-available/devsu.demo /etc/nginx/sites-enabled/ \
    && rm -f /etc/nginx/sites-enabled/default

RUN sed -i "s/<DNS>/$DNS/g" /etc/nginx/sites-available/devsu.demo

# Exponer puertos
EXPOSE 80 8080

#################################
### Script de inicio
#################################
CMD java -jar /srv/aplicaciones/backend/Backend.jar && nginx -g 'daemon off;'